spring:
  application:
    name: zuul-server
server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
zuul:
  routes:
    ribbon:
      path: /rb/**
      serviceId: ribbon
    feign:
      path: /fe/**
      serviceId: feign