spring:
  application:
    name: jap
  datasource:
    url: jdbc:mysql://193.112.214.43:3306/testdb?useUnicode=true&characterEncoding=utf-8
    username: lumia
    password: lumia830
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 8087
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
