spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zczeng/lumia/
          search-paths: config
          username: zczeng
          password: lumia830lumia+-
      label: master
server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/